name: Deploy
on:
  push:
    branches:
      - undefined

jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - name: Get source code
        uses: actions/checkout@v2

  Deploy:
    runs-on: ubuntu-latest
    needs: Setup
    environment: production
    steps:
      - name: Get source code
        uses: actions/checkout@v2
