version: '3.7'

networks:
  app_network:

services:
  ws-backend:
    image: ws-backend
    container_name: ws-backend
    ports:
      - 3000:3000
    restart: always
    networks:
      app_network:
    volumes:
      - '.:/app'
